---
title: "R Notebook"
output: html_notebook
---

# Q2
1 -1
2 ans： 0.3678794
3 ans：0.2689414

```{r}
# 1
# What is the value of the Logit for this observation? 
# -1
-1.5+3*1-0.5*5

# 2
# What is the value of the Odds for this observation? 
# ans： 0.3678794
exp(-1.5+3*1-0.5*5)

#3
#What is the value of P(y = 1) for this observation?
#ans：0.2689414
1/(1+exp((-1.5+3*1-0.5*5)*-1))
```

# Q3
create a logistic regression model to predict "PoorCare" using the independent variables "StartedOnCombination" and "ProviderCount". Use the training set we created in the previous video to build the model.

ANS:1.95230
```{r}
# What is the coefficient for "StartedOnCombination"?
# 1.95230
quality = read.csv("data/quality.csv")

#install.packages("caTools")
library(caTools)

set.seed(88)
split = sample.split(quality$PoorCare, SplitRatio = 0.75)
qualityTrain = subset(quality, split == TRUE)
qualityTest = subset(quality, split == FALSE)

QualityLog = glm(PoorCare ~ StartedOnCombination + ProviderCount, data=qualityTrain, family=binomial)
summary(QualityLog)
```

# Q4
1 0.8
2 0.6
3 threshold value decreased(sensitivity decreased)

```{r}
#1
#What is the sensitivity of Confusion Matrix #1?
#ans:0.8
20/25

#2
#What is the specificity of Confusion Matrix #1?
#ans:0.6
15/25

#3
#Did we increase or decrease the threshold value?
#ans:threshold value decreased(sensitivity decreased)

```

# Q5

1 ans:larger t,in this case(0.1,0.5)
2 ans: around(0.05,0.5)
```{r}
# 1 
# Which threshold would you pick if you wanted to correctly identify a small group of patients who are receiving the worst care with high confidence?
# ans:larger t,in this case(0.1,0.5)

# 2
# Which threshold would you pick if you wanted to correctly identify half of the patients receiving poor care, while making as few errors as possible?
# ans: around(0.05,0.5)
```


```{r}
library(ROCR)

qualityTrain = 
ROCRpred = prediction(predictTrain, qualityTest$PoorCare)
ROCRpref = performance(ROCRpred, "tpr","fpr")
plot(ROCRpref,colorize=TRUE,print.cutoffs.at= seq(0,1,0.1),text.adj=c(-0.2,1.7)  )

```

# Q6

What is the AUC of this model on the test set?
ANS:0.7994792

```{r}
QualityLog = glm(PoorCare ~ OfficeVisits + Narcotics, data=qualityTrain, family=binomial)
summary(QualityLog)

library(ROCR)
predictTest = predict(QualityLog, type="response", newdata=qualityTest)
ROCRpredTest = prediction(predictTest, qualityTest$PoorCare)
auc = as.numeric(performance(ROCRpredTest, "auc")@y.values)
```

